---
title: "bm-project"
author: "group-27"
date: "2024-12-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(leaps)
library(broom)
library(GGally)
library(gridExtra)
library(kableExtra)
library(caret)
library(glmnet)
library(tibble)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  warning = FALSE,
  message = FALSE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r, message=FALSE}
data <- read.csv("Project_1_data.csv")

hist_math <- ggplot(data, aes(x = MathScore)) +
  geom_histogram(binwidth = 5, fill = "steelblue", color = "black") +
  labs(title = "Histogram of Math Scores", x = "Math Score", y = "Frequency")

hist_reading <- ggplot(data, aes(x = ReadingScore)) +
  geom_histogram(binwidth = 5, fill = "firebrick", color = "black") +
  labs(title = "Histogram of Reading Scores", x = "Reading Score", y = "Frequency")

hist_writing <- ggplot(data, aes(x = WritingScore)) +
  geom_histogram(binwidth = 5, fill = "darkgreen", color = "black") +
  labs(title = "Histogram of Writing Scores", x = "Writing Score", y = "Frequency")

scatter_math_reading <- ggplot(data, aes(x = ReadingScore, y = MathScore)) +
  geom_point(color = "darkblue") +
  labs(title = "Math Score vs. Reading Score", x = "Reading Score", y = "Math Score")

scatter_reading_writing <- ggplot(data, aes(x = WritingScore, y = ReadingScore)) +
  geom_point(color = "darkred") +
  labs(title = "Reading Score vs. Writing Score", x = "Writing Score", y = "Reading Score")
data <- data %>%
  mutate(across(c(Gender, EthnicGroup, ParentEduc, LunchType, TestPrep, 
                  ParentMaritalStatus, PracticeSport, IsFirstChild, 
                  TransportMeans, WklyStudyHours), as.factor))

pairwise_plots <- ggpairs(data,
  columns = c("MathScore", "ReadingScore", "WritingScore"),
  aes(color = Gender),
  lower = list(continuous = "smooth"),
  upper = list(continuous = "cor"),
  diag = list(continuous = "densityDiag"))
grid.arrange(
  hist_math, hist_reading, hist_writing
)

grid.arrange(
  scatter_math_reading, scatter_reading_writing,
  ncol = 2
)
```


```{r}
data$Gender <- as.factor(data$Gender)
data$EthnicGroup <- as.factor(data$EthnicGroup)
data$ParentEduc <- as.factor(data$ParentEduc)
data$LunchType <- as.factor(data$LunchType)
data$TestPrep <- as.factor(data$TestPrep)
data$ParentMaritalStatus <- as.factor(data$ParentMaritalStatus)
data$PracticeSport <- as.factor(data$PracticeSport)
data$IsFirstChild <- as.factor(data$IsFirstChild)
data$TransportMeans <- as.factor(data$TransportMeans)
data$WklyStudyHours <- as.factor(data$WklyStudyHours)

data <- na.omit(data)
```

```{r}
data[data == "" | data == " "] <- NA
data <- na.omit(data)
```


```{r}
data_dict <- tibble(
  Variable = c(
    "Gender", "EthnicGroup", "ParentEduc", "LunchType", "TestPrep", 
    "ParentMaritalStatus", "PracticeSport", "IsFirstChild", "NrSiblings", 
    "TransportMeans", "WklyStudyHours", "MathScore", "ReadingScore", "WritingScore"
  ),
  Description = c(
    "Gender of the student (male/female)",
    "Ethnic group of the student (group A to E)",
    "Parent(s) education background (from some_highschool to master's degree)",
    "School lunch type (standard or free/reduced)",
    "Test preparation course followed (completed or none)",
    "Parent(s) marital status (married/single/widowed/divorced)",
    "How often the student practices sport (never/sometimes/regularly)",
    "If the child is the first child in the family (yes/no)",
    "Number of siblings the student has (0 to 7)",
    "Means of transport to school (schoolbus/private)",
    "Weekly self-study hours (less that 5 hours; between 5 and 10 hours; more than
10 hours)",
    "Math test score (0-100)",
    "Reading test score (0-100)",
    "Writing test score (0-100)"
  )
)

knitr::kable(data_dict, col.names = c("Variable", "Description"),caption="Data Dictionary",format = "pipe")  %>%
  column_spec(1, width = "16em") %>% 
  column_spec(2, width = "26em")
```


```{r, echo=FALSE}
numeric_summary = data |> 
  summarize(
    NrSiblings_Mean = mean(NrSiblings, na.rm = TRUE),
    NrSiblings_SD = sd(NrSiblings, na.rm = TRUE),
    NrSiblings_Median = median(NrSiblings, na.rm = TRUE),
    NrSiblings_IQR = IQR(NrSiblings, na.rm = TRUE),
    NrSiblings_Max = max(NrSiblings, na.rm = TRUE),
    NrSiblings_Min = min(NrSiblings, na.rm = TRUE),
    
    MathScore_Mean = mean(MathScore, na.rm = TRUE),
    MathScore_SD = sd(MathScore, na.rm = TRUE),
    MathScore_Median = median(MathScore, na.rm = TRUE),
    MathScore_IQR = IQR(MathScore, na.rm = TRUE),
    MathScore_Max = max(MathScore, na.rm = TRUE),
    MathScore_Min = min(MathScore, na.rm = TRUE),
    
    ReadingScore_Mean = mean(ReadingScore, na.rm = TRUE),
    ReadingScore_SD = sd(ReadingScore, na.rm = TRUE),
    ReadingScore_Median = median(ReadingScore, na.rm = TRUE),
    ReadingScore_IQR = IQR(ReadingScore, na.rm = TRUE),
    ReadingScore_Max = max(ReadingScore, na.rm = TRUE),
    ReadingScore_Min = min(ReadingScore, na.rm = TRUE),
    
    WritingScore_Mean = mean(WritingScore, na.rm = TRUE),
    WritingScore_SD = sd(WritingScore, na.rm = TRUE),
    WritingScore_Median = median(WritingScore, na.rm = TRUE),
    WritingScore_IQR = IQR(WritingScore, na.rm = TRUE),
    WritingScore_Max = max(WritingScore, na.rm = TRUE),
    WritingScore_Min = min(WritingScore, na.rm = TRUE)
  )


numeric_table = data.frame(
  Variable = c("NrSiblings", "MathScore", "ReadingScore", "WritingScore"),
  Mean = c(numeric_summary$NrSiblings_Mean, numeric_summary$MathScore_Mean, 
           numeric_summary$ReadingScore_Mean, numeric_summary$WritingScore_Mean),
  SD = c(numeric_summary$NrSiblings_SD, numeric_summary$MathScore_SD, 
         numeric_summary$ReadingScore_SD, numeric_summary$WritingScore_SD),
  Median = c(numeric_summary$NrSiblings_Median, numeric_summary$MathScore_Median, 
             numeric_summary$ReadingScore_Median, numeric_summary$WritingScore_Median),
  IQR = c(numeric_summary$NrSiblings_IQR, numeric_summary$MathScore_IQR, 
          numeric_summary$ReadingScore_IQR, numeric_summary$WritingScore_IQR),
  Max = c(numeric_summary$NrSiblings_Max, numeric_summary$MathScore_Max, 
          numeric_summary$ReadingScore_Max, numeric_summary$WritingScore_Max),
  Min = c(numeric_summary$NrSiblings_Min, numeric_summary$MathScore_Min, 
          numeric_summary$ReadingScore_Min, numeric_summary$WritingScore_Min)
)

knitr::kable(numeric_table, col.names = c("Variable Name", "Mean", "SD", "Median", "IQR", "Max", "Min"), 
             caption = "Summary Statistics for all Numeric Variables", format = "pipe")%>%
  column_spec(1,width="6em")%>%
  column_spec(2,width="6em")%>%
  column_spec(3,width="6em")%>%
  column_spec(4,width="6em")%>%
  column_spec(5,width="6em")%>%
  column_spec(6,width="6em")%>%
  column_spec(7,width="6em")

```


```{r}
categorical_table <- data |> 
  summarize(
    gender_Male = sum(Gender == "male", na.rm = TRUE),
    gender_Female = sum(Gender == "female", na.rm = TRUE),
    
    ethnicgroup_A = sum(EthnicGroup == "group A", na.rm = TRUE),
    ethnicgroup_B = sum(EthnicGroup == "group B", na.rm = TRUE),
    ethnicgroup_C = sum(EthnicGroup == "group C", na.rm = TRUE),
    ethnicgroup_D = sum(EthnicGroup == "group D", na.rm = TRUE),
    ethnicgroup_E = sum(EthnicGroup == "group E", na.rm = TRUE),
    
    parenteduc_SomeHighSchool = sum(ParentEduc == "some college", na.rm = TRUE),
    parenteduc_HighSchool = sum(ParentEduc == "some high School", na.rm = TRUE),
    parenteduc_Associates = sum(ParentEduc == "associate's degree high school", na.rm = TRUE),
    parenteduc_Bachelors = sum(ParentEduc == "bachelor's degree", na.rm = TRUE),
    parenteduc_Masters = sum(ParentEduc == "master's degree", na.rm = TRUE),
    
    lunchtime_Standard = sum(LunchType == "standard", na.rm = TRUE),
    lunchtime_FreeReduced = sum(LunchType == "free/reduced", na.rm = TRUE),
    
    testprep_Completed = sum(TestPrep == "completed", na.rm = TRUE),
    testprep_None = sum(TestPrep == "none", na.rm = TRUE),
    
    parentmaritalstatus_Married = sum(ParentMaritalStatus == "married", na.rm = TRUE),
    parentmaritalstatus_Single = sum(ParentMaritalStatus == "single", na.rm = TRUE),
    parentmaritalstatus_Widowed = sum(ParentMaritalStatus == "widowed", na.rm = TRUE),
    parentmaritalstatus_Divorced = sum(ParentMaritalStatus == "divorced", na.rm = TRUE),
    
    practicesport_Never = sum(PracticeSport == "never", na.rm = TRUE),
    practicesport_Sometimes = sum(PracticeSport == "sometimes", na.rm = TRUE),
    practicesport_Regularly = sum(PracticeSport == "regularly", na.rm = TRUE),
    
    isfirstchild_Yes = sum(IsFirstChild == "yes", na.rm = TRUE),
    isfirstchild_No = sum(IsFirstChild == "no", na.rm = TRUE),
    
    transportmeans_SchoolBus = sum(TransportMeans == "school_bus", na.rm = TRUE),
    transportmeans_Private = sum(TransportMeans == "private", na.rm = TRUE),
    
    wklystudyhours_LessThan5 = sum(WklyStudyHours == "< 5", na.rm = TRUE),
    wklystudyhours_5to10 = sum(WklyStudyHours == "10-May", na.rm = TRUE),
    wklystudyhours_MoreThan10 = sum(WklyStudyHours == "> 10", na.rm = TRUE)
  )


categorical_final <- data.frame(
  Variable = c("Gender Male", "Gender Female",
               "EthnicGroup A", "EthnicGroup B", "EthnicGroup C", "EthnicGroup D", "EthnicGroup E",
               "ParentEduc Some High School", "ParentEduc High School", "ParentEduc Associates", 
               "ParentEduc Bachelors", "ParentEduc Masters", 
               "LunchType Standard", "LunchType Free/Reduced", 
               "TestPrep Completed", "TestPrep None", 
               "ParentMaritalStatus Married", "ParentMaritalStatus Single", "ParentMaritalStatus Widowed", "ParentMaritalStatus Divorced",
               "PracticeSport Never", "PracticeSport Sometimes", "PracticeSport Regularly",
               "IsFirstChild Yes", "IsFirstChild No", 
               "TransportMeans SchoolBus", "TransportMeans Private",
               "WklyStudyHours Less than 5", "WklyStudyHours 5-10", "WklyStudyHours More than 10"),
  Count = c(
    categorical_table$gender_Male, categorical_table$gender_Female,
    categorical_table$ethnicgroup_A, categorical_table$ethnicgroup_B, categorical_table$ethnicgroup_C, categorical_table$ethnicgroup_D, categorical_table$ethnicgroup_E,
    categorical_table$parenteduc_SomeHighSchool, categorical_table$parenteduc_HighSchool, categorical_table$parenteduc_Associates, 
    categorical_table$parenteduc_Bachelors, categorical_table$parenteduc_Masters, 
    categorical_table$lunchtime_Standard, categorical_table$lunchtime_FreeReduced, 
    categorical_table$testprep_Completed, categorical_table$testprep_None, 
    categorical_table$parentmaritalstatus_Married, categorical_table$parentmaritalstatus_Single, categorical_table$parentmaritalstatus_Widowed, categorical_table$parentmaritalstatus_Divorced,
    categorical_table$practicesport_Never, categorical_table$practicesport_Sometimes, categorical_table$practicesport_Regularly,
    categorical_table$isfirstchild_Yes, categorical_table$isfirstchild_No, 
    categorical_table$transportmeans_SchoolBus, categorical_table$transportmeans_Private,
    categorical_table$wklystudyhours_LessThan5, categorical_table$wklystudyhours_5to10, categorical_table$wklystudyhours_MoreThan10
  ),
  Proportion = round(c(
    categorical_table$gender_Male / nrow(data), categorical_table$gender_Female / nrow(data),
    categorical_table$ethnicgroup_A / nrow(data), categorical_table$ethnicgroup_B / nrow(data), categorical_table$ethnicgroup_C / nrow(data), 
    categorical_table$ethnicgroup_D / nrow(data), categorical_table$ethnicgroup_E / nrow(data),
    categorical_table$parenteduc_SomeHighSchool / nrow(data), categorical_table$parenteduc_HighSchool / nrow(data), 
    categorical_table$parenteduc_Associates / nrow(data), categorical_table$parenteduc_Bachelors / nrow(data), 
    categorical_table$parenteduc_Masters / nrow(data),
    categorical_table$lunchtime_Standard / nrow(data), categorical_table$lunchtime_FreeReduced / nrow(data),
    categorical_table$testprep_Completed / nrow(data), categorical_table$testprep_None / nrow(data),
    categorical_table$parentmaritalstatus_Married / nrow(data), categorical_table$parentmaritalstatus_Single / nrow(data),
    categorical_table$parentmaritalstatus_Widowed / nrow(data), categorical_table$parentmaritalstatus_Divorced / nrow(data),
    categorical_table$practicesport_Never / nrow(data), categorical_table$practicesport_Sometimes / nrow(data),
    categorical_table$practicesport_Regularly / nrow(data),
    categorical_table$isfirstchild_Yes / nrow(data), categorical_table$isfirstchild_No / nrow(data),
    categorical_table$transportmeans_SchoolBus / nrow(data), categorical_table$transportmeans_Private / nrow(data),
    categorical_table$wklystudyhours_LessThan5 / nrow(data), categorical_table$wklystudyhours_5to10 / nrow(data), 
    categorical_table$wklystudyhours_MoreThan10 / nrow(data)
  ), 4)
)

knitr::kable(categorical_final, col.names = c("Variable Name and Levels", "Count", "Proportion"), 
             caption = "Summary Statistics for all Categorical Variables", format = "pipe")%>%
  column_spec(1,width="14em")%>%
  column_spec(2,width="14em")%>%
  column_spec(3,width="14em")
  
```


```{r}
math_full_model <- lm(MathScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                        ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                        TransportMeans + WklyStudyHours, data = data)
math_null_model = lm(MathScore ~ 1, data = data)
math_selected_model = step(math_null_model,
scope = list(lower = formula(math_null_model),
upper = formula(math_full_model)))
math_selected_model
```



```{r}
par(mfrow = c(2, 2)) 
plot(math_selected_model)
par(mfrow = c(1, 1))
```

```{r}
reading_full_model <- lm(ReadingScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                        ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                        TransportMeans + WklyStudyHours, data = data)
reading_null_model = lm(ReadingScore ~ 1, data = data)
reading_selected_model = step(reading_null_model,
scope = list(lower = formula(reading_null_model),
upper = formula(reading_full_model)))
reading_selected_model
```


```{r}
par(mfrow = c(2, 2)) 
plot(reading_selected_model)
par(mfrow = c(1, 1))
```

```{r}
writing_full_model <- lm(WritingScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                        ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                        TransportMeans + WklyStudyHours, data = data)
writing_null_model = lm(WritingScore ~ 1, data = data)
writing_selected_model = step(writing_null_model,
scope = list(lower = formula(writing_null_model),
upper = formula(writing_full_model)))
writing_selected_model
```


```{r}
par(mfrow = c(2, 2)) 
plot(writing_selected_model)
par(mfrow = c(1, 1))
```


# Summary of the the predit model

```{r}
model1 <- lm(formula = ReadingScore ~ Gender + EthnicGroup + ParentEduc + 
               LunchType + TestPrep + ParentMaritalStatus + IsFirstChild, data = data)

model2 <- lm(formula = MathScore ~ Gender + EthnicGroup + ParentEduc + 
               LunchType + TestPrep + ParentMaritalStatus + IsFirstChild + WklyStudyHours, 
             data = data)

model3 <- lm(formula = WritingScore ~ Gender + EthnicGroup + ParentEduc + 
               LunchType + TestPrep + ParentMaritalStatus + WklyStudyHours, data = data)
```

# Lasso for Writing

```{r}
set.seed(2024)

lambda_seq <- 10^seq(-3, 0, by = 0.1)

x <- model.matrix(WritingScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                   ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                   TransportMeans + WklyStudyHours, data = data)[, -1]

cv_object <- cv.glmnet(x, data$WritingScore, lambda = lambda_seq, nfolds = 5)

cv_object

tibble(lambda = cv_object$lambda, mean_cv_error = cv_object$cvm) %>%
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point() +
  scale_x_log10() + 
  labs(title = "Cross-Validation Error vs. Lambda",
       x = "Lambda (log scale)", y = "Mean Cross-Validation Error")

min_lambda <- cv_object$lambda.min
min_lambda

fit_bestcv <- glmnet(x, data$WritingScore, lambda = min_lambda)

coef(fit_bestcv)
```

```{r}
writing_lasso_formula <- WritingScore ~ Gender + EthnicGroup + ParentEduc + LunchType
writing_selected_model <- lm(
  formula = WritingScore ~ Gender + EthnicGroup + ParentEduc + LunchType,
  data = data
)

summary(writing_selected_model)
```

# Lasso for Math

```{r}
set.seed(2024)

lambda_seq <- 10^seq(-3, 0, by = 0.1)

x <- model.matrix(MathScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                   ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                   TransportMeans + WklyStudyHours, data = data)[, -1]

cv_object <- cv.glmnet(x, data$MathScore, lambda = lambda_seq, nfolds = 5)

cv_object

tibble(lambda = cv_object$lambda, mean_cv_error = cv_object$cvm) %>%
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point() +
  scale_x_log10() + 
  labs(title = "Cross-Validation Error vs. Lambda",
       x = "Lambda (log scale)", y = "Mean Cross-Validation Error")

min_lambda <- cv_object$lambda.min
min_lambda

fit_bestcv <- glmnet(x, data$MathScore, lambda = min_lambda)

coef(fit_bestcv)
```

```{r}
math_lasso_formula <- MathScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                      ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                      TransportMeans + WklyStudyHours

math_selected_model <- lm(
  formula = math_lasso_formula,
  data = data
)

summary(math_selected_model)
```

# Lasso for Reading

```{r}
set.seed(2024)

lambda_seq <- 10^seq(-3, 0, by = 0.1)

x <- model.matrix(ReadingScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                   ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                   TransportMeans + WklyStudyHours, data = data)[, -1]

cv_object <- cv.glmnet(x, data$ReadingScore, lambda = lambda_seq, nfolds = 5)

cv_object

tibble(lambda = cv_object$lambda, mean_cv_error = cv_object$cvm) %>%
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point() +
  scale_x_log10() + 
  labs(title = "Cross-Validation Error vs. Lambda",
       x = "Lambda (log scale)", y = "Mean Cross-Validation Error")

min_lambda <- cv_object$lambda.min
min_lambda

fit_bestcv <- glmnet(x, data$ReadingScore, lambda = min_lambda)

coef(fit_bestcv)
```

```{r}
reading_lasso_formula <- ReadingScore ~ Gender + EthnicGroup + ParentEduc + LunchType + TestPrep +
                        ParentMaritalStatus + PracticeSport + IsFirstChild + NrSiblings +
                        TransportMeans + WklyStudyHours

reading_selected_model <- lm(
  formula = reading_lasso_formula,
  data = data
)
summary(reading_selected_model)
```

# Test for interaction

```{r}
model2_test<- lm(formula = MathScore ~ Gender + EthnicGroup  + 
               LunchType + TestPrep + ParentEduc * ParentMaritalStatus * IsFirstChild * WklyStudyHours, 
             data = data)
r_squared_model2 <- summary(model2)$adj.r.squared
r_squared_model2_test <- summary(model2_test)$adj.r.squared
cat("Adjusted R-squared for model2:", r_squared_model2, "\n")
cat("Adjuested R-squared for model2 with interaction:", r_squared_model2_test, "\n")
AIC_model2 = AIC(model2)
AIC_model2_test = AIC(model2_test)
cat("AIC for model2:", AIC_model2, "\n")
cat("AIC for model2 with interaction:", AIC_model2_test, "\n")
```
```{r}
summary(data$MathScore)
```

```{r}
data$MathScore_shifted <- data$MathScore + 1
model2_shifted <- lm(MathScore_shifted ~ Gender + EthnicGroup + ParentEduc + 
                       LunchType + TestPrep + ParentMaritalStatus + IsFirstChild + 
                       WklyStudyHours, data = data)
```

```{r}
par(mfrow = c(1, 3))
boxcox(model1, lambda = seq(-2, 2, by = 0.1))  # Range of lambda values
title("Model 1: ReadingScore")
boxcox(model2_shifted, lambda = seq(-2, 2, by = 0.1))  # Range of lambda values
title("Model 2: MathScore")
boxcox(model3, lambda = seq(-2, 2, by = 0.1))  # Range of lambda values
title("Model 3: WritingScore")
par(mfrow = c(1, 1))
```

```{r}
correlation_matrix <- cor(data[, c("MathScore", "WritingScore", "ReadingScore")], use = "complete.obs")

print(correlation_matrix)

library(corrplot)
corrplot(correlation_matrix, method = "circle", type = "upper", tl.col = "black", tl.srt = 45)
```


# Cross-Validation
```{r}
# CV for Math Score
set.seed(2024)
train_control = trainControl(method = "cv", number = 10)
cv_model = train(MathScore ~ Gender + EthnicGroup + ParentEduc + 
               LunchType + TestPrep + ParentMaritalStatus + IsFirstChild + WklyStudyHours, 
             data = data,
method = "lm",
trControl = train_control)
print(cv_model)
```

```{r}
# CV for Reading Score
set.seed(2024)
train_control = trainControl(method = "cv", number = 10)
cv_model = train(ReadingScore ~ Gender + EthnicGroup + ParentEduc + 
               LunchType + TestPrep + ParentMaritalStatus + IsFirstChild,
               data = data,
method = "lm",
trControl = train_control)
print(cv_model)
```

```{r}
# CV for Reading Score
set.seed(2024)
train_control = trainControl(method = "cv", number = 10)
cv_model = train(WritingScore ~ Gender + EthnicGroup + ParentEduc + 
               LunchType + TestPrep + ParentMaritalStatus + WklyStudyHours,
               data = data,
method = "lm",
trControl = train_control)
print(cv_model)
```


# Final Model Summary

```{r}
writing_selected_model %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 4, caption = "Results of Writing Score Model", format = "pipe")
```



```{r}
math_selected_model %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 4, caption = "Results of Math Score Model", format = "pipe")
```

```{r}
reading_selected_model %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 4, caption = "Results of Reading Score Model", format = "pipe")
```